[Metadata]
Name=mytheme
Version=1
ScaleWithDPI=True

[InputPanel]
NormalColor=#cdd6f4
HighlightCandidateColor=#63e2b7
HighlightColor=#00ff00
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Image=panel.png
Color=#4a4a4f
BorderColor=#4a4a4f
BorderWidth=0

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
Image=highlight.png
Color=#4a4a4f

[InputPanel/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[InputPanel/PrevPage]
Image=prev.png

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/NextPage]
Image=next.png

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[Menu]
NormalColor=#cdd6f4
HighlightCandidateColor=#1e1e2e

[Menu/Background]
Color=#4a4a4f
BorderColor=#4a4a4f
BorderWidth=0

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/Highlight]
Color=#4a4a4f

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Separator]
Color=#5e5e66

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5